# Generated by Django 4.1.2 on 2022-11-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards_Honors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('recognition_level', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('proof_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('proof_pdf', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'Awards and Honors',
            },
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('personal_website', models.URLField()),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
            ],
            options={
                'db_table': 'Biography',
            },
        ),
        migrations.CreateModel(
            name='careerSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'Career Summary',
            },
        ),
        migrations.CreateModel(
            name='certifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Transcript', 'Transcript'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('license', 'license')], default='', max_length=50)),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'certifications',
            },
        ),
        migrations.CreateModel(
            name='PhilosophyStatement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statement', models.TextField()),
            ],
            options={
                'db_table': 'Philosophy Statement',
            },
        ),
        migrations.CreateModel(
            name='Professional_Accomplishments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accomplishment', models.TextField()),
                ('proof_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('proof_pdf', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'Professional Accomplishments',
            },
        ),
        migrations.CreateModel(
            name='References_Testimonials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('relationship', models.TextField(choices=[('company', 'company'), ('university', 'university'), ('client', 'client')], default='')),
                ('strengths', models.TextField()),
                ('abilities', models.TextField()),
                ('experience', models.TextField()),
                ('recommendation_letter', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'References and Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('personal_email', models.CharField(default='', max_length=50, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Volunteering_community_service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Volunteering and community service',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('awards_honors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio_app.awards_honors')),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio_app.biography')),
                ('career_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio_app.careersummary')),
                ('certifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio_app.certifications')),
                ('philosophy_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio_app.philosophystatement')),
                ('professional_accomplishments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio_app.professional_accomplishments')),
                ('references_testimonials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio_app.references_testimonials')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio_app.users')),
                ('volunteering_community_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio_app.volunteering_community_service')),
            ],
            options={
                'db_table': 'Portfolio',
            },
        ),
    ]
