# Generated by Django 4.1.2 on 2022-11-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteering_community_service',
            name='date',
        ),
        migrations.AddField(
            model_name='certifications',
            name='discrition',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='professional_accomplishments',
            name='category',
            field=models.CharField(choices=[('company', 'company'), ('university', 'university'), ('client', 'client')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteering_community_service',
            name='date_deb',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteering_community_service',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
