# Generated by Django 4.1.2 on 2022-11-20 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0002_remove_volunteering_community_service_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteering_community_service',
            name='date_deb',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volunteering_community_service',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
