# Generated by Django 4.1.2 on 2022-11-20 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0003_alter_volunteering_community_service_date_deb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certifications',
            old_name='discrition',
            new_name='description',
        ),
        migrations.AddField(
            model_name='biography',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='awards_honors',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='professional_accomplishments',
            name='category',
            field=models.CharField(choices=[('freelance', 'freelance'), ('academic project', 'academic project'), ('personal project', 'personal project'), ('other', 'other')], default='', max_length=50),
        ),
    ]
